### ISSUE TITLE
QuickView.exe E:\pic\foo.png dosen't work

### ISSUE THREAD

**Issue by tql247** [nandemonogatari/QuickView-2.8-modified#1]
When I try to run `QuickView.exe test.png` is not open image but a windows like this 
![image](https://user-images.githubusercontent.com/37873914/113697068-95a06400-9687-11eb-842a-eb4786e3f244.png)

**Comment by nandemonogatari** [comment]
Don't have delphi installed nor do i have internet to download it atm. I'll check next week or so, should be a quick fix.

**Comment by tql247** [comment]
> Don't have delphi installed nor do i have internet to download it atm. I'll check next week or so, should be a quick fix.

Thankssssss

**Comment by nandemonogatari** [comment]
Fixed it.
